name: main

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Set up Qemu for Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # Set up Buildx for Docker
    - name: Set up Buildx for Docker
      uses: docker/setup-buildx-action@v1

    # Make docker builder image
    - name: Build docker builder image
      env:
        DOCKER_BUILDKIT: 1
      run: make .dockerimage-builder

    # Run build
    - name: Run build
      run: make build-docker

    # Run test
    - name: Run tests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: make test-ci-docker

    # Run lint
    - name: Run linting
      run: make lint-docker

    # Run reportcard
    - name: Run reportcard
      run: make reportcard-docker

    # Make release
    - name: Make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      run: make release-docker

    # Login to Docker Hub
    - name: Login to Docker Hub
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Make docker images
    - name: Make docker images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      run: make build-and-push-dockerimages
